package com.superbestfriends.retropoly;

public class Board {
    public static Space spaces[] = {
            new Property("BanjoKazooie", 2),
            new Property("BanjoTooie", 24),
            new Property("Bomberman", 10),
            new Property("ConkersBad", 26),
            new Property("DiddyKong", 22),
            new Property("DonkeyKong", 5),
            new Property("GoldenEye", 30),
            new Property("Kirby", 16),
            new Property("MarioBros", 35),
            new Property("MarioKart", 7),
            new Property("MarioParty", 25),
            new Property("MarioTennis", 15),
            new Property("MortalKombat", 1),
            new Property("PaperMario", 3),
            new Property("PerfectDark", 28),
            new Property("PokemonSnap", 17),
            new Property("PokemonStadium", 29),
            new Property("Resident", 12),
            new Property("StarFox", 8),
            new Property("StarWars", 19),
            new Property("StarWarsShadows", 13),
            new Property("SuperSmash", 33),
            new Property("Yoshi", 21),
            new Property("Zelda", 34),
            new Property("Trello",4),
            new Property ("Bloomberg", 14),
            new Property("SendGrid",23),
            new Property("BrainTree",31),
            new Space("JAIL", 9),
            new Space("GO", 0),
            new Space ("PARKING", 18),
            new Space ("POLICE",27),
            new Space("BLANK1", 6),
            new Space ("BLANK2", 20),
            new Space ("TAX1", 11),
            new Space ("TAX2",32),
    };
}
